language: python
python:
  - "2.7"
sudo: false

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install pip --upgrade
  - pip install setuptools
  - python setup.py sdist
  - pip install dist/ga4gh_common*.tar.gz
# every installable in setup.py's entry_points should be tested here
  - ga4gh_run_tests --version

before_script:
  - pip install -r dev-requirements.txt


# run_tests.py runs everything under the script: tag so only put commands
# under it that we want to run (and want to be able to run) as local tests
script: 
  - flake8 run_tests_dev.py setup.py ga4gh tests
  - nosetests tests
        --with-coverage --cover-package ga4gh.common
        --cover-inclusive --cover-min-percentage=70
        --cover-branches --cover-erase

deploy:
    provider: pypi
    user: dannycolligan
    password:
        secure: eRwj4i4/uNblvFux88f/pcX1VUvZuu4e89yVHabcl8g4xY82+iLo7NAFdTQ6qn/Xx+H9NsyK2yaMqy+8vV/XDC0ZUaRwWPy1nby2oJtYxsBg8IekMlvPWRPXASsFD1a4+7BCQfYrNRc01lmQETGocSP29MQVZH2EhnCASwH7qj5dpymIHh0aJbwwe6eL5eurKnRKU+4ZR4wZPYledl43TlR9u3QOKo4lUQIR7/3Nd0aNLLyt7o5p5czDwRsrUCncPlmEURwauZlWMu4k1HUMunZdU/HB/h/EwfLCizhVMSZNGFJobV0v/K9xW+FnWV6xZecLTY2RgmTc8PO8gPhFi6p1yz2SM2bU0rxoiDKHJDHK6d6uvJ7t4MJb/gEg+nJV6BFgcdiFmQGwGpCndsSJWMatRPc+JeAkrmC22dy2c/Zn1u1DK7Jpolec6h2KbMikjPj5ih23c85bRsukAfOLhwnCWIrRlG720TojPZ2BanInoJs8J0t9zu3268f3/wwzde31pHuzzU9WC9ODfGWOLGAUqP2XnrabPij4zHtIFQyDu+61PwR3BlwD6TlsX80eojGaM8fk5HEg5PmvYlfbYScm8Wz16wb+NXZqoZI7/Cc0et1Igpvh/8Fxws/cchQeN0Ec7jnGDq+xfrjIaCHywOPwiSbZe05S3QfDvKM+TrE=
    on:
        tags: true
